version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: egresso_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ucasdatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/main/resources/database:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
