spring.application.name=egresso
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/portal_egressos}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver
